name: Process Airtable Data

on:
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R dependencies
        run: |
          Rscript -e "install.packages('httr')"
          Rscript -e "install.packages('jsonlite')"

      - name: Run R script
        env:
          AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        run: Rscript Scripts/airtable_and_r_github_wo_rairtable.R