name: Run R Script with Airtable PAT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev pkg-config libjpeg-dev libpng-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.2'  # Use a stable R version

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("httr", "jpeg", "png", "rairtable", "dplyr", "readr"), repos="https://cloud.r-project.org", dependencies=TRUE)'

    - name: Create Dataout directory
      run: mkdir -p Dataout

    - name: Clean Dataout directory
      run: rm -rf Dataout/*  # Optional: Clears the directory before running the script

    - name: Debug PAT secret
      run: |
        if [ -z "${{ secrets.AIRTABLE_PAT }}" ]; then
          echo "AIRTABLE_PAT is not set."
          exit 1
        else
          echo "AIRTABLE_PAT is set."
        fi

    - name: Debug BASE_ID secret
      run: |
        if [ -z "${{ secrets.AIRTABLE_BASE_ID }}" ]; then
          echo "AIRTABLE_BASE_ID is not set."
          exit 1
        else
          echo "AIRTABLE_BASE_ID is set."
        fi

    - name: Run R script
      run: |
        Rscript Scripts/airtable_and_r_github.R
      env:
        AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: data-output
        path: Dataout/


