name: Run R Script with Airtable PAT

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev pkg-config libjpeg-dev libpng-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.3'  # Specify the R version you need


    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("httr", "jpeg", "png", "rairtable"), repos="https://cloud.r-project.org", dependencies=TRUE)'
        
    - name: Create Dataout directory
      run: mkdir -p Dataout

#    - name: Debug secret
#      run: |
#        echo "AIRTABLE_PAT: $AIRTABLE_PAT"

    - name: Run R script
      run: |
        Rscript Scripts/airtable_and_r_simple.R
 #     env:
#        AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}

    - name: Commit data to repository
      env:
        WHO_DAILY_DASH_AUTOMATION_TOKEN: ${{ secrets.AIRTABLE_R_AUTOMATION_TOKEN }}
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add Dataout/*.csv
        git commit -m "Update WHO data"
        git push https://${{ secrets.secrets.AIRTABLE_R_AUTOMATION_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

