name: Process Airtable Data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          install.packages(c("httr", "jsonlite"))

      - name: Run R script
        env:
          AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        run: Rscript process_airtable_data.R
