name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-install-packages:
    uses: ./.github/workflows/install_packages.yml
    with:
      r_script: "Scripts/airtable_and_r.R"  # Path to the R script to run
