name: Run R Script with GitHub PAT

on: [push]

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.3'  # Replace with your R version

    - name: Install required R packages
      run: |
        R -e "install.packages('httr', repos='https://cloud.r-project.org', dependencies=TRUE)"

    - name: Check if httr is installed
      run: |
        R -e "library(httr)"

    - name: Run R script
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: |
        Rscript Scripts/setup_env.R